service: authorization-service
frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1
  stage: dev

plugins:
  - serverless-dotenv-plugin

functions:
  basicAuthorizer:
    handler: handler.basicAuthorizer
