service: parser
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  stage: dev
  environment:
    FILE_UPLOAD_BUCKET_NAME: ${self:custom.fileBucketName}

plugins:
  - serverless-iam-roles-per-function

custom:
  fileBucketName: aws-course-file-storage 

functions:
  parser:
    handler: handler.parser
    events:
      - s3:
          bucket: ${self:custom.fileBucketName}
          event: s3:ObjectCreated:*
          rules:
            - prefix: upload/
          existing: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - "s3:*"
        Resource: 
          - arn:aws:s3:::${self:custom.fileBucketName}/*
