service: parser-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: dev
  environment:
    FILE_UPLOAD_BUCKET_NAME: aws-course-files
    SQS_NEW_PRODUCT_URL:
      Ref: NewProductSQSQueue

plugins:
  - serverless-iam-roles-per-function

resources:
  Resources:
    NewProductSQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: catalogItemsQueue
  Outputs:
    NewProductSQSQueueArn:
      Value:
        Fn::GetAtt: [NewProductSQSQueue, Arn]

iamRoleStatements:
  - Effect: "Allow"
    Action: "s3:ListBucket"
    Resource:
      - "arn:aws:s3:::aws-course-files"
  - Effect: "Allow"
    Action:
      - "s3:*"
    Resource:
      - "arn:aws:s3:::aws-course-files/*"
  - Effect: "Allow"
    Action: "sqs:*"
    Resource:
      - Fn::GetAtt: [NewProductSQSQueue, Arn]

functions:
  parser:
    handler: handler.parser
    events:
      - s3:
          bucket: aws-course-files
          event: s3:ObjectCreated:*
          rules:
            - prefix: upload/
          existing: true
